
import { Sanitizer } from '@jupyterlab/apputils';
import { IRenderMime } from '@jupyterlab/rendermime';


export class PyRopeSanitizer extends Sanitizer {
    private _pyrope_options: IRenderMime.ISanitizerOptions = {
        // See https://github.com/jupyterlab/jupyterlab/blob/8f78e2708cafface8191773e8d5045936e46b0d1/packages/apputils/src/sanitizer.ts#L587
        allowedAttributes: {
            '*': [
                'class',
                'dir',
                'draggable',
                'hidden',
                'id',
                'inert',
                'itemprop',
                'itemref',
                'itemscope',
                'lang',
                'spellcheck',
                'style',
                'title',
                'translate',
            ],
            a: [
                'accesskey',
                'coords',
                'href',
                'hreflang',
                'name',
                'rel',
                'shape',
                'tabindex',
                'target',
                'type',
            ],
            area: [
                'accesskey',
                'alt',
                'coords',
                'href',
                'nohref',
                'shape',
                'tabindex',
            ],
            audio: [
                'autoplay',
                'controls',
                'loop',
                'mediagroup',
                'muted',
                'preload',
                'src',
            ],
            bdo: ['dir'],
            blockquote: ['cite'],
            br: ['clear'],
            button: [
                'accesskey',
                'data-commandlinker-args',
                'data-commandlinker-command',
                'disabled',
                'name',
                'tabindex',
                'type',
                'value',
            ],
            canvas: ['height', 'width'],
            caption: ['align'],
            col: ['align', 'char', 'charoff', 'span', 'valign', 'width'],
            colgroup: ['align', 'char', 'charoff', 'span', 'valign', 'width'],
            command: [
                'checked',
                'command',
                'disabled',
                'icon',
                'label',
                'radiogroup',
                'type',
            ],
            data: ['value'],
            del: ['cite', 'datetime'],
            details: ['open'],
            dir: ['compact'],
            div: ['align'],
            dl: ['compact'],
            fieldset: ['disabled'],
            font: ['color', 'face', 'size'],
            form: [
                'accept',
                'autocomplete',
                'enctype',
                'method',
                'name',
                'novalidate',
            ],
            h1: ['align'],
            h2: ['align'],
            h3: ['align'],
            h4: ['align'],
            h5: ['align'],
            h6: ['align'],
            hr: ['align', 'noshade', 'size', 'width'],
            iframe: [
                'align',
                'frameborder',
                'height',
                'marginheight',
                'marginwidth',
                'width',
            ],
            img: [
                'align',
                'alt',
                'border',
                'height',
                'hspace',
                'ismap',
                'name',
                'src',
                'usemap',
                'vspace',
                'width',
            ],
            input: [
                'accept',
                'accesskey',
                'align',
                'alt',
                'autocomplete',
                'checked',
                'disabled',
                'inputmode',
                'ismap',
                'list',
                'max',
                'maxlength',
                'min',
                'multiple',
                'name',
                'placeholder',
                'readonly',
                'required',
                'size',
                'src',
                'step',
                'tabindex',
                'type',
                'usemap',
                'value',
            ],
            ins: ['cite', 'datetime'],
            label: ['accesskey', 'for'],
            legend: ['accesskey', 'align'],
            li: ['type', 'value'],
            map: ['name'],
            menu: ['compact', 'label', 'type'],
            meter: ['high', 'low', 'max', 'min', 'value'],
            ol: ['compact', 'reversed', 'start', 'type'],
            optgroup: ['disabled', 'label'],
            option: ['disabled', 'label', 'selected', 'value'],
            output: ['for', 'name'],
            p: ['align'],
            pre: ['width'],
            progress: ['max', 'min', 'value'],
            q: ['cite'],
            select: [
                'autocomplete',
                'disabled',
                'multiple',
                'name',
                'required',
                'size',
                'tabindex',
            ],
            source: ['type'],
            span: ['data-pyrope-field-name', 'data-pyrope-format-spec'],
            table: [
                'align',
                'bgcolor',
                'border',
                'cellpadding',
                'cellspacing',
                'frame',
                'rules',
                'summary',
                'width',
            ],
            tbody: ['align', 'char', 'charoff', 'valign'],
            td: [
                'abbr',
                'align',
                'axis',
                'bgcolor',
                'char',
                'charoff',
                'colspan',
                'headers',
                'height',
                'nowrap',
                'rowspan',
                'scope',
                'valign',
                'width',
            ],
            textarea: [
                'accesskey',
                'autocomplete',
                'cols',
                'disabled',
                'inputmode',
                'name',
                'placeholder',
                'readonly',
                'required',
                'rows',
                'tabindex',
                'wrap',
            ],
            tfoot: ['align', 'char', 'charoff', 'valign'],
            th: [
                'abbr',
                'align',
                'axis',
                'bgcolor',
                'char',
                'charoff',
                'colspan',
                'headers',
                'height',
                'nowrap',
                'rowspan',
                'scope',
                'valign',
                'width',
            ],
            thead: ['align', 'char', 'charoff', 'valign'],
            tr: ['align', 'bgcolor', 'char', 'charoff', 'valign'],
            track: ['default', 'kind', 'label', 'srclang'],
            ul: ['compact', 'type'],
            video: [
                'autoplay',
                'controls',
                'height',
                'loop',
                'mediagroup',
                'muted',
                'poster',
                'preload',
                'src',
                'width',
            ]
        },
    }

    sanitize(dirty: string, options?: IRenderMime.ISanitizerOptions): string {
        return super.sanitize(
            dirty, { ...this._pyrope_options, ...(options || {}) }
        );
    }
}
